server:
  port: 0
spring:
  application:
    name: fudly-listing-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/fudly
  datasource:
    url: jdbc:postgresql://localhost:5432/listing_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  outbox:
    topic: listing-events
    batch-size: 100
    fixed-delay-ms: 1000
    requeue-delay-ms: 30000
    lease-time-minutes: 1